#!/usr/bin/env python3
"""Import "Unnamed Trivia RPG Game - Sheet1.csv" into a Godot GDScript
question bank (client/game_data.gd).

CSV layout: header, then Character, Question, Option_0..3, Answer,
Difficulty. Rows whose Character contains 'special' are design ideas with
no answer and are excluded. Run from the server repo root:
    python3 tools/import_questions.py "Unnamed Trivia RPG Game - Sheet1.csv"
"""
import csv
import json
import re
import sys

PLAYER_SET = []


def esc(s: str) -> str:
    return __import__("json").dumps(s, ensure_ascii=False)


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("usage: import_questions.py <csv>")
    rows = list(csv.reader(open(sys.argv[1], encoding="utf-8-sig")))
    trainers = {}
    for r in rows[2:]:
        if not r or not r[0] or not r[0].strip():
            continue
        ch = r[0].strip()
        q = (r[1] or "").strip()
        if "special" in ch.lower() or "sepcial" in ch.lower() or not q:
            continue
        ans = (r[5] or "").strip() if len(r) > 5 else ""
        if not ans:
            continue
        opts = [(r[2 + i] or "").strip() for i in range(4)]
        wrong = [o for o in opts if o and o.upper() != ans.upper()]
        slug = re.sub(r"[^A-Za-z0-9]+", "", ch).lower()[:20]
        trainers.setdefault(ch, []).append(
            {"id": slug, "question": q, "correct": ans, "wrong": wrong})

    total = sum(len(v) for v in trainers.values())
    out = ["extends RefCounted", "",
           "## Real question bank generated by tools/import_questions.py from",
           "## \"Unnamed Trivia RPG Game - Sheet1.csv\" (%d questions, %d trainers)." % (total, len(trainers)),
           "## Special (\"order these\") rows are design ideas and were excluded.",
           "## Re-run the importer to regenerate from a fresh export.",
           ""]
    out.append("const TRAINERS := {")
    for ch, qs in sorted(trainers.items(), key=lambda x: -len(x[1])):
        out.append("    %s: [" % esc(ch))
        for i, q in enumerate(qs):
            q = dict(q)
            q["id"] = "%s%d" % (q["id"], i)
            out.append("        %s," % json.dumps(q, ensure_ascii=False))
        out.append("    ],")
    out.append("}")
    out.append("")
    out.append("")
    out.append("static func choices(q: Dictionary) -> Array:")
    out.append("\tvar c: Array = [q[\"correct\"]]")
    out.append("\tc.append_array(q[\"wrong\"])")
    out.append("\tc.shuffle()")
    out.append("\treturn c")
    out.append("")
    with open("client/game_data.gd", "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("wrote client/game_data.gd: %d questions, %d trainers" % (total, len(trainers)))


main()